name: reviewdog
on: [pull_request]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run detect-secrets with reviewdog
      uses: reviewdog/action-detect-secrets@v0.11.5
      with:
        reporter: github-pr-review # Change reporter.
